# Generated by Django 4.2 on 2023-04-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('tower', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.apartment')),
                ('owners', models.ManyToManyField(to='entrance.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.apartment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrance.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='apartments',
            field=models.ManyToManyField(through='entrance.Ownership', to='entrance.apartment'),
        ),
        migrations.CreateModel(
            name='NonResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('id_photo', models.ImageField(upload_to='nonresidents')),
                ('plate_photo', models.ImageField(upload_to='nonresidents')),
                ('type', models.CharField(choices=[('visit', 'Visit'), ('supplier', 'Supplier'), ('event_attendee', 'Event Attendee')], max_length=50)),
                ('apartment_visiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_nonresidents', to='entrance.apartment')),
            ],
        ),
    ]
